---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false

install:
  - npm install

script:
  - npm test
  - docker login -u mrrusof -p $DOCKER_PWD
  - make push
